### ISSUE TITLE
Author adjustment

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/AFHTTPRequestOperationManager-HYPGoldenRetriever#2]
We should probably use `Hyper Interaktiv AS` instead of `Hyper AS`, similar to our LICENSEs.

**Comment by zenangst** [comment]
Good point!

**Comment by timkurvers** [comment]
:+1:

**Comment by 3lvis** [comment]
Also fixed in our template

https://github.com/hyperoslo/pod-template/blob/master/README.md
